#!/usr/bin/env bash
# _config.sh - Three-tier configuration for claude-git-workflow scripts
# Usage: sourced automatically by _common.sh -- do not source directly
#
# Resolution order (highest to lowest priority):
#   1. Environment variables (CGW_*)       -- CI/automation overrides
#   2. Config file ($PROJECT_ROOT/.cgw.conf) -- generated by configure.sh
#   3. Built-in defaults                   -- works without any config
#
# All scripts work out of the box with defaults. Run configure.sh once
# to auto-detect your project's settings and generate .cgw.conf.

# ============================================================================
# PROJECT ROOT AUTO-DETECTION
# ============================================================================
# Resolve the repository the caller is standing in, matching git's own
# discovery (Pro Git ch. 10: with GIT_DIR unset, "Git walks up the directory
# tree until it gets to ~ or /, looking for a .git directory at every step" —
# starting from the cwd). The scripts' bare git commands operate on the cwd
# repo, so config, logs, and backup tags must resolve against that same repo —
# never against wherever the script files happen to live (symlinked or shared
# scripts/git installs would otherwise read another repo's .cgw.conf).

_detect_project_root() {
  local root
  # Primary: git's own discovery from the cwd. Also handles linked worktrees
  # and submodules, where .git is a file — invisible to a `-d .git` test.
  if root="$(git rev-parse --show-toplevel 2>/dev/null)" && [[ -n "${root}" ]]; then
    echo "${root}"
    return 0
  fi
  # Fallback (cwd outside any work tree): walk up from SCRIPT_DIR, covering
  # the standard install where scripts/git/ lives inside the project.
  local dir
  dir="$(cd "${SCRIPT_DIR}" && pwd)"
  while [[ "${dir}" != "/" ]] && [[ -n "${dir}" ]]; do
    if [[ -e "${dir}/.git" ]]; then
      echo "${dir}"
      return 0
    fi
    dir="$(dirname "${dir}")"
  done
  echo "[ERROR] Cannot find git repository root from ${PWD} or ${SCRIPT_DIR}" >&2
  return 1
}

# cgw_main_worktree_root — resolve the MAIN worktree's absolute path, usable
# from any worktree of the repo.
#
# `git worktree list --porcelain`'s first entry is always the main worktree
# (documented git behavior) — this holds for --separate-git-dir clones and
# submodules too, unlike deriving it from `dirname "$(git rev-parse
# --git-common-dir)"`, which assumes the common dir's parent is the worktree
# root and breaks for those layouts. Callers needing the main worktree's
# scripts/git or .cgw.conf (both gitignored, so absent from linked worktrees)
# should use this rather than re-deriving it. Lives here (not _common.sh)
# because the .cgw.conf fallback below runs during _config.sh's own
# evaluation, before _common.sh has sourced it.
#
# Args:
#   $1 (optional) — resolve relative to this path instead of the caller's cwd.
#     Lets a caller validate an arbitrary target path before cd-ing into it.
# Output: absolute path to the main worktree, on stdout.
# Returns: 0 on success; 1 if $1 (or cwd) is not inside a git worktree.
cgw_main_worktree_root() {
  local from="${1:-.}"
  local raw
  raw="$(git -C "${from}" worktree list --porcelain 2>/dev/null | head -1)" || return 1
  [[ -z "${raw}" ]] && return 1
  echo "${raw#worktree }"
}

# Allow tests (and CI overrides) to pin PROJECT_ROOT via env var, skipping auto-detection.
if [[ -z "${PROJECT_ROOT:-}" ]]; then
  PROJECT_ROOT="$(_detect_project_root)" || exit 1
fi

# ============================================================================
# CONFIG FILE LOADING
# ============================================================================
# Source .cgw.conf if it exists. Variables already set in the environment
# (env vars take priority) are NOT overwritten because bash ${VAR:-} syntax
# checks for unset-or-empty, but env vars that ARE set skip the defaults block.
# We achieve true "env wins" by only sourcing variables the env hasn't set yet.

_CGW_CONF="${PROJECT_ROOT}/.cgw.conf"

# Linked-worktree fallback: .cgw.conf is gitignored, so git never checks it
# out into a linked worktree. Without this, a worktree of a project that
# gitignores it would silently run with built-in defaults instead of the
# project's real CGW_LOCAL_FILES / CGW_EXTRA_PREFIXES / etc. This does NOT
# violate the anti-goal in the block comment above (never resolve against
# wherever the scripts happen to live) -- the main worktree is the SAME
# repository as PROJECT_ROOT, just a different checkout of it, not some
# other repo's shared/symlinked install. Only attempted when PROJECT_ROOT is
# itself a linked worktree (main root differs), so the common case --
# PROJECT_ROOT IS the main worktree, e.g. the run_script test helper pinning
# PROJECT_ROOT to its own temp repo -- never invokes this.
if [[ ! -f "${_CGW_CONF}" ]]; then
  _cgw_main_root="$(cgw_main_worktree_root "${PROJECT_ROOT}" 2>/dev/null)" || _cgw_main_root=""
  if [[ -n "${_cgw_main_root}" ]] && [[ "${_cgw_main_root}" != "${PROJECT_ROOT}" ]] && [[ -f "${_cgw_main_root}/.cgw.conf" ]]; then
    _CGW_CONF="${_cgw_main_root}/.cgw.conf"
  fi
  unset _cgw_main_root
fi

if [[ -f "${_CGW_CONF}" ]]; then
  # Read .cgw.conf line-by-line, only applying variables not already set in the environment.
  # This ensures env vars take priority AND derived values (e.g. CGW_PROTECTED_BRANCHES
  # referencing CGW_TARGET_BRANCH) stay consistent with the values actually used.
  while IFS= read -r _line || [[ -n "${_line}" ]]; do
    _line="${_line%$'\r'}"                         # tolerate CRLF .cgw.conf (e.g., touched by a Windows editor)
    [[ "${_line}" =~ ^[[:space:]]*# ]] && continue # skip comments
    [[ "${_line}" =~ ^[[:space:]]*$ ]] && continue # skip blank lines
    # Only accept CGW_* assignment lines (optionally prefixed with export).
    # Reject anything else to prevent eval of arbitrary shell statements.
    if [[ "${_line}" =~ ^[[:space:]]*(export[[:space:]]+)?(CGW_[A-Z0-9_]+)=(.*) ]]; then
      _cgw_var="${BASH_REMATCH[2]}"
      _cgw_val="${BASH_REMATCH[3]}"
      # Only set if not already in environment (preserves env var priority)
      if [[ -z "${!_cgw_var+x}" ]]; then
        # Strip surrounding quotes and any trailing inline comment (` # …`).
        # Quoted form: take content of the first balanced "…" or '…', discard the rest.
        # Unquoted form: strip from the first space-hash onwards.
        if [[ "${_cgw_val}" =~ ^\"([^\"]*)\" ]]; then
          _cgw_val="${BASH_REMATCH[1]}"
        elif [[ "${_cgw_val}" =~ ^\'([^\']*)\' ]]; then
          _cgw_val="${BASH_REMATCH[1]}"
        else
          _cgw_val="${_cgw_val%%[[:space:]]#*}"               # strip ` #comment`
          _cgw_val="${_cgw_val%"${_cgw_val##*[![:space:]]}"}" # rtrim
        fi
        printf -v "${_cgw_var}" '%s' "${_cgw_val}"
        export "${_cgw_var?}"
      fi
    else
      printf '%s\n' "[WARN] Ignoring unsupported line in .cgw.conf: ${_line}" >&2
    fi
  done <"${_CGW_CONF}"
  unset _line _cgw_var _cgw_val
fi

# ============================================================================
# CONFIG REGISTRY -- the single list of CGW_* settings and their facts
# ============================================================================
# One row per setting: name|default|kind|empty|scope
#   kind   str | bool (0/1) | int (non-negative) | enum:a/b/... | computed
#          (computed: default derived below from other settings or the repo,
#          e.g. the target branch; the registry only records that it exists)
#   empty  keep -- an explicitly empty value (CGW_X="") is honoured, e.g. an
#                  empty CGW_LINT_CMD disables lint
#          fill -- an empty value falls back to the default
#   scope  conf -- a persistent setting: belongs in .cgw.conf, is shown in
#                  cgw.conf.example and the docs options table
#          env  -- a per-run switch (CGW_SKIP_LINT=1 ...): docs table only
# Defaults, validation, cgw.conf.example, docs/configuration.md and the
# configure.sh generator are all checked against this table by
# tests/unit/config_registry.bats -- add a setting here first.
_CGW_REGISTRY='CGW_SOURCE_BRANCH||str|fill|conf
CGW_TARGET_BRANCH||computed|fill|conf
CGW_REMOTE|origin|str|fill|conf
CGW_LOCAL_FILES|CLAUDE.md MEMORY.md .claude/ logs/|str|fill|conf
CGW_LOCAL_FILES_EXEMPT||str|fill|conf
CGW_EXTRA_PREFIXES||str|fill|conf
CGW_FREEFORM_MESSAGE_BRANCHES||str|fill|conf
CGW_FREEFORM_MESSAGE_CHECK||str|fill|conf
CGW_LINT_CMD|ruff|str|keep|conf
CGW_LINT_CHECK_ARGS|check {files}|str|keep|conf
CGW_LINT_FIX_ARGS|check --fix {files}|str|keep|conf
CGW_LINT_EXCLUDES|--extend-exclude logs --extend-exclude .venv|str|keep|conf
CGW_FORMAT_CMD|ruff|str|keep|conf
CGW_FORMAT_CHECK_ARGS|format --check {files}|str|keep|conf
CGW_FORMAT_FIX_ARGS|format {files}|str|keep|conf
CGW_FORMAT_EXCLUDES|--exclude logs --exclude .venv|str|keep|conf
CGW_MARKDOWNLINT_NPX_FALLBACK|1|bool|keep|conf
CGW_MARKDOWNLINT_CMD||computed|keep|conf
CGW_MARKDOWNLINT_ARGS|!CLAUDE.md !MEMORY.md|str|keep|conf
CGW_MARKDOWNLINT_PATHS|**/*.md|str|keep|conf
CGW_MARKDOWNLINT_FIX_ARGS|--fix|str|keep|conf
CGW_LINT_EXTENSIONS|*.py|str|keep|conf
CGW_SKIP_LINT|0|bool|keep|env
CGW_SKIP_MD_LINT|0|bool|keep|env
CGW_SKIP_TYPECHECK|0|bool|keep|env
CGW_ALL|0|bool|keep|env
CGW_ALLOW_STAGED_DIVERGENCE|0|bool|keep|conf
CGW_COMMIT_SUBJECT_SOFT_LEN|50|int|keep|conf
CGW_COMMIT_SUBJECT_HARD_LEN|72|int|keep|conf
CGW_ENFORCE_SUBJECT_LENGTH|1|bool|keep|conf
CGW_TYPECHECK_CMD||str|keep|conf
CGW_TYPECHECK_CHECK_ARGS|check|str|keep|conf
CGW_TYPECHECK_EXCLUDES||str|keep|conf
CGW_MERGE_CONFLICT_STYLE||computed|fill|conf
CGW_MERGE_IGNORE_WHITESPACE|0|bool|fill|conf
CGW_DOCS_PATTERN||str|fill|conf
CGW_DEV_ONLY_FILES||str|fill|conf
CGW_ALLOW_LOCAL_FILES_IN_MERGE|0|bool|keep|conf
CGW_CLEANUP_TESTS|0|bool|fill|conf
CGW_PROTECTED_BRANCHES||computed|fill|conf
CGW_MERGE_MODE|direct|enum:direct/pr|fill|conf
CGW_SIGN_COMMITS|0|bool|fill|conf
CGW_SIGN_TAGS|0|bool|fill|conf
CGW_ALLOW_REBASE_PUBLISHED|0|bool|fill|conf
CGW_AUTO_REMOVE_INDEX_LOCK|1|bool|fill|conf
CGW_INDEX_LOCK_MAX_AGE_SECONDS|30|int|fill|conf
CGW_INDEX_LOCK_WAIT_SECONDS|10|int|fill|conf
CGW_LOCK_RETRY_ATTEMPTS|3|int|fill|conf
CGW_LOCK_RETRY_DELAY|1|int|fill|conf
CGW_NON_INTERACTIVE|0|bool|fill|env
CGW_NO_VENV|0|bool|fill|env
CGW_STAGED_ONLY|0|bool|fill|env'
# Prints the table (builtins only -- _config.sh is sourced by every script).
cgw_config_registry() { printf '%s\n' "${_CGW_REGISTRY}"; }

# Apply every registry default (computed settings are handled further down),
# then validate by kind: a bad int, bool or enum value warns and resets to its
# default.
_cgw_apply_registry_defaults() {
  local name default kind empty
  while IFS='|' read -r name default kind empty _; do
    [[ "${kind}" == "computed" ]] && continue
    if [[ "${empty}" == "keep" ]]; then
      [[ -z "${!name+x}" ]] && printf -v "${name}" '%s' "${default}"
    else
      [[ -z "${!name:-}" ]] && printf -v "${name}" '%s' "${default}"
    fi
    local expected=""
    case "${kind}" in
      int)
        if ! [[ "${!name}" =~ ^[0-9]+$ ]]; then
          printf '[WARN] %s has non-numeric value "%s"; resetting to %s\n' \
            "${name}" "${!name}" "${default}" >&2
          printf -v "${name}" '%s' "${default}"
          export "${name?}"
        fi
        ;;
      bool)
        # An explicitly empty kept bool is honoured (scripts only act on "1").
        [[ -z "${!name}" || "${!name}" == 0 || "${!name}" == 1 ]] || expected="0 or 1"
        ;;
      enum:*)
        [[ "/${kind#enum:}/" == *"/${!name}/"* ]] || expected="${kind#enum:}"
        ;;
    esac
    if [[ -n "${expected}" ]]; then
      printf '[WARN] %s has invalid value "%s" (expected %s); resetting to %s\n' \
        "${name}" "${!name}" "${expected}" "${default}" >&2
      printf -v "${name}" '%s' "${default}"
      export "${name?}"
    fi
  done <<<"${_CGW_REGISTRY}"
}

# ============================================================================
# DEFAULTS (applied only if still unset after env + config)
# ============================================================================

# --- Branch names ---
# SOURCE has no default -- it's an inherently per-operation choice ("what am I merging"),
# not a repo-wide fact. Scripts that need a default when no --source flag is given must
# handle an empty CGW_SOURCE_BRANCH explicitly (see validate_branch_pair in _common.sh,
# which reports a clear "no source branch configured" error instead of guessing).
# Legacy CLAUDE_GIT_* env vars map onto their CGW_* equivalents before the
# registry fills defaults (a legacy "1" wins over the "0" default).
# shellcheck disable=SC2034  # consumed by the sourcing scripts (cross-file)
{
  if [[ "${CLAUDE_GIT_NON_INTERACTIVE:-0}" == "1" ]]; then CGW_NON_INTERACTIVE=1; fi
  if [[ "${CLAUDE_GIT_NO_VENV:-0}" == "1" ]]; then CGW_NO_VENV=1; fi
  if [[ "${CLAUDE_GIT_STAGED_ONLY:-0}" == "1" ]]; then CGW_STAGED_ONLY=1; fi
}
_cgw_apply_registry_defaults

# TARGET is a repo-wide fact ("which branch is stable") and IS auto-detected here so every
# script gets a sensible value without requiring .cgw.conf to pin it down.
# Resolution: ${CGW_REMOTE}/HEAD symbolic ref -> local 'main' -> local 'master' -> 'main'.
# Uses `git -C` (not bare cwd-relative git) because this runs at source time, before any
# script's main() has cd'd into PROJECT_ROOT.
if [[ -z "${CGW_TARGET_BRANCH:-}" ]]; then
  _cgw_remote_for_detect="${CGW_REMOTE:-origin}"
  _cgw_detected_target="$(git -C "${PROJECT_ROOT}" symbolic-ref --quiet --short "refs/remotes/${_cgw_remote_for_detect}/HEAD" 2>/dev/null)" || _cgw_detected_target=""
  _cgw_detected_target="${_cgw_detected_target#"${_cgw_remote_for_detect}"/}"
  if [[ -z "${_cgw_detected_target}" ]]; then
    if git -C "${PROJECT_ROOT}" show-ref --verify --quiet refs/heads/main 2>/dev/null; then
      _cgw_detected_target="main"
    elif git -C "${PROJECT_ROOT}" show-ref --verify --quiet refs/heads/master 2>/dev/null; then
      _cgw_detected_target="master"
    else
      _cgw_detected_target="main"
    fi
  fi
  CGW_TARGET_BRANCH="${_cgw_detected_target}"
  unset _cgw_remote_for_detect _cgw_detected_target
fi

# --- Remote name ---
# Override with CGW_REMOTE=upstream (or any remote name) for fork-based workflows.

# --- Local-only files (space-separated; trailing / denotes a directory) ---
# These files are never committed. configure.sh auto-detects project-specific ones.

# --- Exempt files (exact paths allowed through CGW_LOCAL_FILES protection) ---

# --- Commit message prefixes ---
# Standard conventional commit prefixes (always included):
_CGW_BASE_PREFIXES="feat|fix|docs|chore|test|refactor|style|perf"
# Project-specific extras (pipe-separated, e.g. "cuda|tensorrt"):
if [[ -n "${CGW_EXTRA_PREFIXES}" ]]; then
  CGW_ALL_PREFIXES="${_CGW_BASE_PREFIXES}|${CGW_EXTRA_PREFIXES}"
else
  CGW_ALL_PREFIXES="${_CGW_BASE_PREFIXES}"
fi
export CGW_ALL_PREFIXES # consumed by commit_enhanced.sh (cross-file, not detectable by shellcheck)

# --- Freeform-message branches ---
# Space-separated bash glob patterns of branch names whose commit MESSAGE
# FORMAT is not checked (conventional-commit grammar, subject-length hard
# cap). Everything else still applies: lint, local-only files, protected
# branches. Use for branches that target another project with its own
# commit-message style (e.g. an upstream PR branch). Example: "up/* upstream/*"
# Optional: a command run against the message on a freeform branch instead of
# skipping validation entirely, e.g. the target project's own commit-msg hook.
# Receives the message as a file path in $1. Relative paths resolve against
# PROJECT_ROOT. Empty (default): no check runs.
export CGW_FREEFORM_MESSAGE_BRANCHES CGW_FREEFORM_MESSAGE_CHECK # consumed by commit_enhanced.sh, undo_last.sh, hooks/pre-push (cross-file, not detectable by shellcheck)

# --- Lint configuration ---
# Set CGW_LINT_CMD="" to disable lint checks entirely (e.g. non-Python projects
# that haven't configured a linter yet).
# Use +x (not :-) to distinguish "unset" from "explicitly set to empty string".
# The "{files}" token marks where a scoped file list is substituted (audit mode
# expands it to "."); a legacy standalone "." also still works. See _common.sh
# cgw_strip_path_arg / cgw_fill_path_placeholder.

# Set CGW_FORMAT_CMD="" to disable formatting checks.
# Use +x (not :-) to distinguish "unset" from "explicitly set to empty string".

# Set CGW_MARKDOWNLINT_CMD to enable a dedicated markdown lint step.
# Unset (never configured -- the common case, since configure.sh writes no
# CGW_MARKDOWNLINT_CMD line) = auto-detect a markdownlint binary on PATH,
# falling back to `npx --yes markdownlint-cli2` when node is available (see
# _cgw_detect_markdownlint below). This is what lets an already-installed
# project pick up markdown lint on the next scripts/ refresh with no .cgw.conf
# edit -- mirrors how CGW_TARGET_BRANCH is auto-detected above. Explicitly set
# to "" in .cgw.conf or the environment to opt out and keep the step disabled.
# Use +x (not :-) to distinguish "unset" from "explicitly set to empty string".
_cgw_node_supports_markdownlint() {
  command -v node >/dev/null 2>&1 && node -e 'new RegExp("", "v")' >/dev/null 2>&1
}

_cgw_detect_markdownlint() {
  if command -v markdownlint-cli2 >/dev/null 2>&1; then
    echo "markdownlint-cli2"
  elif command -v markdownlint >/dev/null 2>&1; then
    echo "markdownlint"
  elif [[ "${CGW_MARKDOWNLINT_NPX_FALLBACK}" != "0" ]] && command -v npx >/dev/null 2>&1; then
    if _cgw_node_supports_markdownlint; then
      echo "npx --yes markdownlint-cli2"
    else
      echo ""
    fi
  else
    echo ""
  fi
}
if [[ -z "${CGW_MARKDOWNLINT_CMD+x}" ]]; then
  CGW_MARKDOWNLINT_CMD="$(_cgw_detect_markdownlint)"
fi
# CGW_MARKDOWNLINT_ARGS holds flags/exclusions ONLY — always applied, never
# replaced by a file list. CGW_MARKDOWNLINT_PATHS is the default scan target,
# used only in audit/whole-repo mode (no explicit file list). The commit gate
# passes staged *.md files instead of the PATHS glob, so an unrelated markdown
# violation elsewhere no longer blocks a code-only commit.
# CGW_MARKDOWNLINT_FIX_ARGS is the --fix invocation, applied the same way
# CHECK_ARGS is (scoped file list in commit/modified-only mode, PATHS glob in
# audit mode). Works unchanged for both markdownlint-cli2 and markdownlint.
# Migration guard: the old single-var shape conflated the scan glob with
# exclusions. Warn only on a bare glob token (exclusions like "!*.tmp" and
# flags are legitimate ARGS content and must not trigger this). Tokenize with
# read (not an unquoted for-loop) so globs are never expanded against the cwd.
_cgw_md_toks=()
read -r -a _cgw_md_toks <<<"${CGW_MARKDOWNLINT_ARGS}" || true
for _cgw_md_tok in "${_cgw_md_toks[@]+"${_cgw_md_toks[@]}"}"; do
  case "${_cgw_md_tok}" in
    '!'* | -*) : ;;
    *'*'*)
      echo "[cgw-config] WARNING: CGW_MARKDOWNLINT_ARGS contains a path glob ('${_cgw_md_tok}'). Move the scan target to CGW_MARKDOWNLINT_PATHS; ARGS is now flags/exclusions only." >&2
      break
      ;;
  esac
done
unset _cgw_md_tok _cgw_md_toks

# --- Modified-only lint file extensions ---
# Space-separated glob patterns used by check_lint.sh / fix_lint.sh --modified-only.
# Default matches Python files. Override for other languages (e.g. "*.js *.ts" or "*.go").

# --- Runtime gate defaults (single source of truth) ---
# These were previously only defaulted inline in callers via ${VAR:-...}, with no
# definition here. Centralized so there is one authoritative default; callers keep
# their inline fallbacks as defense-in-depth. Use +x to preserve an explicit empty.

# --- Staged-blob congruence guard (commit_enhanced.sh) ---
# commit_enhanced.sh's code-quality checks validate the WORKING TREE, but
# `git commit` records the INDEX. In a genuine --staged-only commit (partial
# `git add -p`), CGW cannot tell "the user meant index != working tree" apart
# from "a stale/unvalidated blob is about to be committed", so it fails closed
# by default. Set to "1" to instead commit the staged blob as-is with a
# warning. Bulk (--all) and --only commits are unaffected -- both stage
# whole files, so the guard re-stages and re-verifies automatically there.

# --- Commit subject length (commit_enhanced.sh) ---
# Pro Git's "Commit Guidelines" recommend keeping the subject line (the part
# after the "type:" prefix) to ~50 chars; git log --oneline and the GitHub UI
# commonly truncate around 72. Below CGW_COMMIT_SUBJECT_SOFT_LEN: silent.
# Between soft and hard: non-blocking advisory tip. Past
# CGW_COMMIT_SUBJECT_HARD_LEN: blocks via cgw_confirm (non-interactive: abort)
# when CGW_ENFORCE_SUBJECT_LENGTH=1 (default) -- set to 0 to keep it advisory-only.

# --- Typecheck step (non-blocking pre-commit hook) ---
# Empty CGW_TYPECHECK_CMD = typecheck step skipped. Example: "pyrefly".

# --- Merge conflict style (merge_with_validation.sh) ---
# Set to "merge" for git's default two-way markers (accepted explicitly, same
# effect as leaving this empty), "diff3" to show the common-ancestor version
# in conflict markers (Pro Git recommended), or "zdiff3" for the same view
# with non-conflicting hunks collapsed (git >= 2.35 -- falls back to diff3
# with a warning on older git). Empty = git default (two-way markers, same as
# "merge").
CGW_MERGE_CONFLICT_STYLE="${CGW_MERGE_CONFLICT_STYLE:-}"

# Reject unsupported style values (silently ignored by git otherwise) and
# downgrade zdiff3 -> diff3 when the installed git predates 2.35.
_cgw_git_supports_zdiff3() {
  local ver
  ver="$(git version 2>/dev/null | sed -n 's/^git version \([0-9][0-9.]*\).*/\1/p')"
  [[ -n "${ver}" ]] || return 1
  [[ "$(printf '%s\n%s\n' "2.35" "${ver}" | sort -V | head -n1)" == "2.35" ]]
}
_cgw_validate_merge_conflict_style() {
  case "${CGW_MERGE_CONFLICT_STYLE}" in
    "" | merge | diff3 | zdiff3) ;;
    *)
      printf '[WARN] CGW_MERGE_CONFLICT_STYLE has unsupported value "%s"; ignoring (expected: merge, diff3, zdiff3)\n' \
        "${CGW_MERGE_CONFLICT_STYLE}" >&2
      CGW_MERGE_CONFLICT_STYLE=""
      ;;
  esac
  if [[ "${CGW_MERGE_CONFLICT_STYLE}" == "zdiff3" ]] && ! _cgw_git_supports_zdiff3; then
    printf '[WARN] CGW_MERGE_CONFLICT_STYLE=zdiff3 requires git >= 2.35; falling back to diff3\n' >&2
    CGW_MERGE_CONFLICT_STYLE="diff3"
  fi
}
_cgw_validate_merge_conflict_style
unset -f _cgw_validate_merge_conflict_style _cgw_git_supports_zdiff3

# --- Merge whitespace handling (merge_with_validation.sh) ---
# Set to "1" to add -Xignore-space-change to the merge command.
# Prevents false conflicts caused by whitespace-only differences.

# --- Docs CI validation (merge_with_validation.sh) ---
# Extended regex for allowed doc filenames. Empty = skip validation entirely.
# Example: "^(README\.md|.*_GUIDE\.md|.*_REFERENCE\.md)$"

# --- Dev-only file exclusions for cherry-pick warnings ---
# Space-separated paths. Empty = no warning. Example: "tests/ pytest.ini"

# --- Local-only file guard for merge / cherry-pick ---
# Set to "1" to allow a merge or cherry-pick to carry CGW_LOCAL_FILES into shared
# history (the guard otherwise aborts in non-interactive mode). Default 0.

# --- Tests directory cleanup on target branch ---
# 0 = disabled (default), 1 = remove tests/ from target if gitignored

# --- Force-push protected branches (space-separated) ---
# Branches requiring explicit --force flag + confirmation for force-push.
CGW_PROTECTED_BRANCHES="${CGW_PROTECTED_BRANCHES:-${CGW_TARGET_BRANCH}}"

# --- Merge mode ---
# "direct": merge locally via merge_with_validation.sh (default, no PR required)
# "pr":     create a GitHub PR via create_pr.sh (triggers Charlie CI + GitHub Actions)

# --- Commit and tag signing ---
# GPG/SSH signing of commits and tags, matching Pro Git §"Signing Your Work".
# CGW_SIGN_COMMITS: 0 = off (default), 1 = pass -S to git commit.
# CGW_SIGN_TAGS:    0 = off (default), 1 = use git tag -s instead of -a.
# Both settings are additive: they never disable git's native commit.gpgsign/
# tag.gpgsign config. Override per-invocation via --sign / --no-sign flags.
# The signing key is whatever git is configured with (gpg.format, user.signingkey).

# --- Published-commit rebase guard ---
# CGW_ALLOW_REBASE_PUBLISHED: 0 = enforce (default), 1 = allow rebasing commits
# already pushed to CGW_REMOTE.  Override in CI if you control a shared force-push workflow.

# --- Stale index.lock auto-recovery ---
# CGW scripts detect and remove abandoned .git/index.lock files left by
# crashed or killed git processes (the most common Claude Code failure mode).
#
# Safety guards: removal is refused if a rebase/merge/cherry-pick/revert/bisect
# operation is currently in progress (state dirs/sentinels detected in .git/).
# Locks newer than MAX_AGE are given WAIT_SECONDS to clear before removal.
#
# Set CGW_AUTO_REMOVE_INDEX_LOCK=0 to disable auto-removal (warn-only mode).
#
# --- Index lock race retry ---
# CGW_LOCK_RETRY_ATTEMPTS: number of retry attempts for mutating git commands
# when encountering an in-flight index.lock race or transient collision (default 3).
# CGW_LOCK_RETRY_DELAY: base delay in seconds between retries with backoff (default 1).

# Callers source this file under `set -e`: always finish on a zero status,
# whatever the last conditional above evaluated to.
true
